;; http://stackoverflow.com/questions/8483182/evil-mode-best-practice
(define-key evil-insert-state-map "\C-a" 'evil-beginning-of-line)
(define-key evil-insert-state-map "\C-e" 'evil-end-of-line)
(define-key evil-normal-state-map "\C-e" 'evil-end-of-line)
(define-key evil-visual-state-map "\C-e" 'evil-end-of-line)
(define-key evil-motion-state-map "\C-e" 'evil-end-of-line)
;; (define-key evil-normal-state-map "\C-f" 'evil-forward-char)
;; (define-key evil-insert-state-map "\C-f" 'evil-forward-char)
;; (define-key evil-insert-state-map "\C-f" 'evil-forward-char)
;; (define-key evil-normal-state-map "\C-b" 'evil-backward-char)
;; (define-key evil-insert-state-map "\C-b" 'evil-backward-char)
;; (define-key evil-visual-state-map "\C-b" 'evil-backward-char)
(define-key evil-normal-state-map "\C-d" 'evil-delete-char)
(define-key evil-insert-state-map "\C-d" 'evil-delete-char)
(define-key evil-visual-state-map "\C-d" 'evil-delete-char)
;; (define-key evil-normal-state-map "\C-n" 'evil-next-line)
;; (define-key evil-insert-state-map "\C-n" 'evil-next-line)
;; (define-key evil-visual-state-map "\C-n" 'evil-next-line)
;; (define-key evil-normal-state-map "\C-p" 'evil-previous-line)
;; (define-key evil-insert-state-map "\C-p" 'evil-previous-line)
;; (define-key evil-visual-state-map "\C-p" 'evil-previous-line)

;; UNDO/REDO
(define-key evil-normal-state-map (kbd "C-z") 'undo-tree-undo)
(define-key evil-insert-state-map (kbd "C-z") 'undo-tree-undo)
(define-key evil-visual-state-map (kbd "C-z") 'undo-tree-undo)
(define-key evil-normal-state-map (kbd "C-S-z") 'undo-tree-redo)
(define-key evil-insert-state-map (kbd "C-S-z") 'undo-tree-redo)
(define-key evil-visual-state-map (kbd "C-S-z") 'undo-tree-redo)

;;  (defun delete-line-no-kill ()
;;    (delete-region (point) (line-end-position)))
;;  (global-set-key (kbd "C-k") 'delete-line-no-kill)
(global-set-key (kbd "C-k") 'delete-line-no-kill)

;; Adds Sublime text like line movement capabilities
(global-set-key (kbd "<C-s-up>") 'move-text-line-up)
(global-set-key (kbd "<C-s-down>") 'move-text-line-down)
