# Path to your oh-my-zsh installation.
export ZSH=$HOME/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="anmol"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=~/oh-my-zsh/custom

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git github python sublime colored-man-pages zsh-autosuggestions zsh-syntax-highlighting history-substring-search z zaw osx)
#plugins=(git zsh-syntax-highlighting github last-working-dir python sublime)
source $ZSH/oh-my-zsh.sh

# User configuration

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zshconfig="subl ~/.zshrc"

#autoloads the ~/dotfiles/functions directory 
export FPATH=~/dotfiles/functions:$FPATH
autoload -Uz ~/dotfiles/functions/**/[^_+]*(N^/:t) zmv edit-command-line

#lines added to remove use of sudo with npm install
#NPM_PACKAGES="${HOME}/.npm-packages"
#NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
#PATH="$NPM_PACKAGES/bin:$PATH"
#MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

#list installed node packages
alias npl="npm list -g --depth=0"

########## Adding your Own ##############
##########      RULES	   ##############

#Better copy command
alias xclip="xclip -selection c"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="localip() {ifconfig | grep 'inet ' | tail -n 1 | awk '{print \$2}'};localip"

# File size
alias fs="stat -f \"%z bytes\""

# Fixes vim colors in tmux mode
export TERM="xterm-256color"

# User Git Aliases
alias gbd='git-better-diff'

# Pipe my public key to my clipboard.
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"

# Pipe AWS OTP into the system clipboard.
alias awsotp="aws_otp | tee >(pbcopy) && echo '=> Copied AWS OTP to pasteboard.'"
alias vpnotp="vpn_otp | tee >(pbcopy) && echo '=> Copied VPN OTP to pasteboard.'"
alias vpn2otp="vpn2_otp | tee >(pbcopy) && echo '=> Copied VPN OTP to pasteboard.'"

# stop completion for zsh on certain commands.
alias ssh='nocorrect ssh'
alias retry='nocorrect retry'

# fixes .z files in the $HOME directory
export _Z_DATA="/Users/anmol.j/dotfiles/zsh/z/.z"

# Recursively delete `.DS_Store` files
#alias cleanup_dsstore="find . -name '*.DS_Store' -type f -ls -delete"

# Source the configuration from grc to color the default linux commands
#source /usr/local/etc/grc.bashrc
