# Path variables
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Path added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Path for user installed Binaries
export PATH=$PATH:~/dotfiles/bin 

# Path for user installed binaries that are executables
export PATH=$PATH:~/dotfiles/external_bin

# Adds the Latex binaries to PATH
export PATH=$PATH:/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin

# Adds path for GO installation
export PATH=$PATH:/usr/local/opt/go/libexec/bin

# Lines added to remove use of sudo with npm install
export NPM_PACKAGES="${HOME}/.npm-packages"
export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
export PATH="$NPM_PACKAGES/bin:$PATH"
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

# added by Miniconda3 4.3.21 installer
export PATH="/Users/anmol.j/miniconda3/bin:$PATH"
